export enum RelationTypes {
    None = 0,
    Synonym,
    Acronym,
    Compound,
    Variation,
    Singular,
    Plural,
    JamaGhairNadai,
    WahidGhairNadai,
    JamaIstasnai,
    OppositeGender,
    FormOfFeal,
    Halat,
    HalatMafooli,
    HalatIzafi,
    HalatTafseeli,
    JamaNadai,
    HalatFaili,
    HalatTakhsis,
    WahidNadai,
    Takabuli,
    Usage
}
